# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ponder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ponder
	pod 'Hero'
  pod 'IQKeyboardManagerSwift'

  target 'PonderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PonderUITests' do
    # Pods for testing
  end

end
